apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-depl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      name: nodejs-pod
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: bharath195/nodejsapp
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsservice
spec:
  selector:
    app: nodejs
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort



